CREATE TABLE todos 
(
    id INTEGER AUTO_INCREMENT,
    content VARCHAR(100) NOT NULL,
    status ENUM("active", "done") NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB;